apiVersion: v1
kind: Pod
metadata:
  name: demo-app-secret-env
spec:
  containers:
    - name: demo-app
      image: ngana0/demo-app:v1.0.0
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
