apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-app-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: demo-app
              image: ngana0/demo-app:v1.0.0
          restartPolicy: OnFailure
