apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprobe
spec:
  containers:
    - name: app-container
      image: ngana0/demo-app:v1.0.0
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 15