apiVersion: v1
kind: Pod
metadata:
  name: demo-app-resources
spec:
  containers:
    - name: demo-app
      image: ngana0/demo-app:v1.0.0
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "0.5"
          memory: "512Mi"
