apiVersion: batch/v1
kind: Job
metadata:
  name: demo-app-job
spec:
  template:
    spec:
      containers:
        - name: demo-app
          image: ngana0/demo-app:v1.0.0
      restartPolicy: Never
